name: ci
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        go-version:
          - 1.17.x
          - 1.16.x
          - 1.15.x
        os:
          - ubuntu

    name: build (${{ matrix.os }}/go-${{ matrix.go-version }})
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - run: go build

  test:
    strategy:
      matrix:
        go-version:
          - 1.17.x
          - 1.16.x
          - 1.15.x
        os:
          - ubuntu

    name: test (${{ matrix.os }}/go-${{ matrix.go-version }})
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - run: go test

  qa:
    strategy:
      matrix:
        go-version:
          - 1.17.x
        os:
          - ubuntu

    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then echo "Go code is not formatted"; exit 1; fi
    - run: go vet
    - run: go get honnef.co/go/tools/cmd/staticcheck
    - run: staticcheck
    - run: go get mvdan.cc/unparam
    - run: unparam
